#!/bin/bash

# Custom script to correctly launch XUBUNTU session


export DEFAULTS_PATH=/usr/share/gconf/xubuntu.default.path
export MANDATORY_PATH=/usr/share/gconf/xubuntu.mandatory.path
export GDMSESSION=xubuntu

export DESKTOP_SESSION=xubuntu
export XDG_CONFIG_DIRS=/etc/xdg/xdg-xubuntu:/etc/xdg:/etc/xdg
export XDG_DATA_DIRS=/usr/share/xubuntu:/usr/local/share/:/usr/share/:/usr/share

exec /usr/bin/startxfce4

# vim: set ts=4 sts=4 sw=4 noet:
