---
#
### Docker integration
#

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Add provisioning user to the docker group
  user:
    name: "{{ GISLAB_PROVISIONING_USER }}"
    groups: docker
    append: yes


- name: Create docker directory
  file:
    path: "{{ docker_dir }}"
    state: directory
    mode: 0755

# vim: set ts=8 sts=2 sw=2 et:
