# -*- mode: ruby -*-
# vi: set ft=ruby :

# TODO: upgrade to Ubuntu Trusty

Vagrant.require_version ">= 1.7.0"

BOX = "precise-canonical-32"
BOX_URL = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box"


Vagrant.configure(2) do |config|
  # fix for https://github.com/ansible/ansible/issues/8644
  ENV['PYTHONIOENCODING'] = "utf-8"

  config.vm.box = BOX
  config.vm.box_url = BOX_URL
  config.vm.synced_folder '.', '/vagrant'
  config.vm.hostname = "gislab-mobile"

  config.ssh.forward_agent = true

    config.vm.define "gislab-mobile" do |server|
      # provisioning
      server.vm.provision "install", type: "ansible" do |ansible|
        ansible.playbook = "gislab-mobile.yml"
        ansible.verbose = "vv"
      end

      # VirtualBox configuration
      server.vm.provider "virtualbox" do |vb, override|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
#       vb.gui = true
      end
    end
end
