#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


# usage
function usage() {
    echo "USAGE: $(basename $0) [OPTIONS] group"
    echo "Create GIS.lab group."
    echo "Group name can contain only lower case digits and numbers."
    echo -e "\nOPTIONS
    -d group description (optional)
    -h display this help
    "
    exit 255
}


# options
while getopts "d:h" OPTION
do
    case "$OPTION" in
        d) GISLAB_GROUP_DESCRIPTION="$OPTARG" ;;
        h) usage ;;
        \?) exit 1 ;;
    esac
done
shift $(($OPTIND - 1))
if [ $# -eq 0 ]; then usage; fi

GISLAB_GROUP=$1


lds="ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:///"

# sanity checks
if [ "$($lds "(&(objectClass=posixGroup)(cn=$GISLAB_GROUP))")" != "" ]; then
    gislab_print_error "Group '$GISLAB_GROUP' already exists"
fi

if ! [[ "$GISLAB_GROUP" =~ ^[a-z][a-z0-9_]*$ ]]; then
    gislab_print_error "Invalid characters in group name"
fi


### LDAP
gislab_print_info "Adding group"

# create LDAP group
ldapaddgroup $GISLAB_GROUP

if [ -n "$GISLAB_GROUP_DESCRIPTION" ]; then
    ldapmodifygroup $GISLAB_GROUP > /dev/null << EOL
changetype: modify
add: description
description: $GISLAB_GROUP_DESCRIPTION
EOL
fi


# confirmation message
gislab_print_info "Group '$GISLAB_GROUP' was successfully created"

# vim: set ts=8 sts=4 sw=4 et:
