#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


echo "This is a list of available GIS.lab administrator commands.
To get more information run command with '-h' option."

for file in $GISLAB_PATH_ADMIN/gislab-*; do
    if [ $file != "$0" ]; then
        echo -e "* $(basename $file)"
    fi
done

echo

# vim: set ts=8 sts=4 sw=4 et:
