#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


# usage
function usage() {
    echo "USAGE: $(basename $0) [OPTIONS]"
    echo "List GIS.lab users."
    echo -e "\nOPTIONS
    -g list only members of group
    -h display this help
    "
    exit 255
}


# options
while getopts "g:h" OPTION
do
        case "$OPTION" in
            g) GISLAB_GROUP=$OPTARG ;;
            h) usage ;;
            \?) exit 1;;
        esac
done


lds="ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:///"

if [ -n "$GISLAB_GROUP" ]; then
    # sanity checks
    if [ "$($lds "(&(objectClass=posixGroup)(cn=$GISLAB_GROUP))")" == "" ]; then
        gislab_error "Group '$GISLAB_GROUP' does not exists"
    fi

    # list users belonging to group
    for user in \
            $($lds "(&(objectClass=posixGroup)(cn=$GISLAB_GROUP))" memberUid \
            | grep -v "^dn:" \
            | awk -F ":" '{print $2}'); do
        $lds "(&(objectClass=posixAccount)(uid=$user))"
    done
else
    # list all users
    lsldap -u
fi

# vim: set ts=8 sts=4 sw=4 et:
