#!/bin/bash
# Backup all GIS.lab user's accounts and system files.

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


### USAGE
function usage() {
    echo "USAGE: $(basename $0)"
    echo "Backup all GIS.lab user's accounts and system files."
    echo -e "\nOPTIONS
    -d backup directory (optional, default: /storage/backup)
    -h display this help
    "
    exit 255
}


### OPTIONS
opt_backup_dir="$GISLAB_PATH_BACKUP"

while getopts "d:h" OPTION
do
    case "$OPTION" in
        d) opt_backup_dir="$OPTARG" ;;
        h) usage ;;
        \?) exit 1 ;;
    esac
done


### VARIABLES
date=$(date '+%Y-%m-%d:%H-%M-%S')
tmp_dir=${opt_backup_dir}/${GISLAB_UNIQUE_ID}-${date}.backup
system_backup_file=$opt_backup_dir/$GISLAB_UNIQUE_ID-$date.tar
lds="ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:///"


## MAIN SCRIPT
mkdir -p $opt_backup_dir
chmod 700 $opt_backup_dir

mkdir -p $tmp_dir


# backup all user accounts
for user in \
        $($lds "(objectClass=posixAccount)" uid \
        | awk '/^uid: / { print $2 }'); do
    gislab-backupuser -d $opt_backup_dir $user
done


# backup content of secret directory after running user accounts backups
cd $tmp_dir

echo $GISLAB_VERSION > $tmp_dir/GISLAB_VERSION
tar -cjf $tmp_dir/gislab.tar.bz2 $GISLAB_PATH_SECRET

tar -cf $system_backup_file *
chmod 400 $system_backup_file

touch $opt_backup_dir/$GISLAB_UNIQUE_ID-$date.done

rm -rf $tmp_dir


### CONFIRMATION MESSAGE
gislab_info "Backup of system files created in '$system_backup_file'"

# vim: set ts=8 sts=4 sw=4 et:
