#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


### USAGE
function usage() {
    echo "USAGE: $(basename $0)"
    echo "Upgrade GIS.lab system."
    echo -e "\nOPTIONS
    -h  display this help
    "
    exit 255
}


### OPTIONS
while getopts "h" OPTION
do
    case "$OPTION" in
        h) usage ;;
        \?) exit 255 ;;
    esac
done


### SANITY CHECKS
clients="$(gislab-cluster members -status=alive -tag role=client)"
if [ -n "$clients" ]; then
    gislab_error "
        Some GIS.lab client machines are running. Can't perform upgrade
    "
    exit 1
fi


### MAIN SCRIPT
# upgrade server packages
gislab_info "Upgrading server packages ..."
apt --assume-yes --force-yes update
apt --assume-yes --force-yes dist-upgrade
apt --assume-yes --force-yes autoremove


# upgrade client packages
gislab_info "Upgrading client packages ..."

# detect if there are any upgradeable packages before running upgrade
gislab-client-shell apt --assume-yes --force-yes update

packages="$(gislab-client-shell apt-show-versions -u -b 2>/dev/null)"
if [ -n "$packages" ]; then
    # upgrade client chroot
    gislab-client-shell apt --assume-yes --force-yes dist-upgrade
    gislab-client-shell apt --assume-yes --force-yes autoremove

    # rebuild client image
    gislab-client-image
fi


### CONFIRMATION MESSAGE
gislab_success "GIS.lab system upgrade was successfully done"

# vim: set ts=8 sts=4 sw=4 et:
