#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


### USAGE
function usage() {
    echo "USAGE: $(basename $0) [OPTIONS] username"
    echo "Delete GIS.lab user account."
    echo -e "\nOPTIONS
    -b  backup user data
    -f  force running this command (do not ask before deleting account)
    -h  display this help
    "
    exit 255
}


### OPTIONS
opt_force="no"
while getopts "bhf" OPTION
do
    case "$OPTION" in
        b) opt_backup="yes" ;;
        f) opt_force="yes" ;;
        h) usage ;;
        \?) exit 1;;
    esac
done
shift $(($OPTIND - 1))
if [ $# -eq 0 ]; then usage; fi

GISLAB_USER=$1


### VARIABLES
lds="ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:///"


### SANITY CHECKS
if [ "$($lds "(&(objectClass=posixAccount)(uid=$GISLAB_USER))")" == "" ]; then
    gislab_error "User '$GISLAB_USER' does not exists"
fi

if [ -f $GISLAB_PATH_HOME/${GISLAB_USER}/.gislab/session.lock ]; then
    gislab_error "GIS.lab user '$GISLAB_USER' is still running session"
fi


### USER CONFIRMATION
if [ "$opt_force" != "yes" ]; then
    gislab_warning "
        This command will completely remove user account
        '$GISLAB_USER' including all data
    "
    echo "Continue ? [ENTER to continue, CTRL-C to cancel]"
    read
fi

### MAIN SCRIPT
# export variables
export GISLAB_USER


# perform backup
if [ "$opt_backup" == "yes" ]; then
    gislab-backupuser $GISLAB_USER
fi


# execute before-delete hooks
if [ -d $GISLAB_PATH_CUSTOM/accounts/before-delete ]; then
    gislab_info "Running 'before-delete' account hooks"
    run-parts $GISLAB_PATH_CUSTOM/accounts/before-delete || true
fi


# LDAP
gislab_info "Deleting user account"

# disable forwarding system mails to user and remove user
# from superuser's group, if user was superuser
if [ "$($lds "(&(objectClass=posixGroup)(cn=gislabadmins)(memberUid=$GISLAB_USER))")" != "" ]; then
    gislab-moduser -S $GISLAB_USER
fi

# manunaly delete user from additional groups
# (bug https://bugs.launchpad.net/ubuntu/+source/ldapscripts/+bug/1292143)
groups="$($lds "(&(objectClass=posixGroup)(memberUid=$GISLAB_USER))" memberUid \
    | sed -n 's/^dn: cn=\(.*\),ou=.*$/\1/p' \
    | tr '\n' ',' \
    | sed 's/,$//')"

if [ -n "$groups" ]; then
    gislab-moduser -A $groups $GISLAB_USER
fi

# remove LDAP account
ldapdeleteuser $GISLAB_USER


# run deluser hook
$GISLAB_PATH_SYSTEM/accounts/hooks/deluser.sh $GISLAB_USER


# execute after-delete hooks
if [ -d $GISLAB_PATH_CUSTOM/accounts/after-delete ]; then
    gislab_info "Running 'after-delete' account hooks"
    run-parts $GISLAB_PATH_CUSTOM/accounts/after-delete || true
fi


### CONFIRMATION MESSAGE
gislab_info "Account '$GISLAB_USER' was successfully deleted"

# vim: set ts=8 sts=4 sw=4 et:
