#!/bin/bash

set -e

source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


# usage
function usage() {
    echo "USAGE: $(basename $0) [OPTIONS] group"
    echo "Delete GIS.lab group. Only empty group can be deleted."
    echo -e "\nOPTIONS
    -f  force running this command (do not ask before deleting group)
    -h  display this help
    "
    exit 255
}


# options
FORCE="no"
while getopts "hf" OPTION
do
        case "$OPTION" in
            f) FORCE="yes" ;;
            h) usage ;;
            \?) exit 1;;
        esac
done
shift $(($OPTIND - 1))
if [ $# -eq 0 ]; then usage; fi

GISLAB_GROUP=$1


lds="ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:///"

# sanity checks
if [ "$($lds "(&(objectClass=posixGroup)(cn=$GISLAB_GROUP))")" == "" ]; then
    gislab_print_error "Group '$GISLAB_GROUP' does not exists"
fi

if [ "$($lds "(&(objectClass=posixGroup)(cn=$GISLAB_GROUP))" memberUid \
        | grep -v "^dn:")" != "" ]; then
    gislab_print_error "Group '$GISLAB_GROUP' has a members"
fi


if [ "$FORCE" != "yes" ]; then
    gislab_print_warning "This command will remove group '$GISLAB_GROUP'"
    echo "Continue ? [ENTER to continue, CTRL-C to cancel]"
    read
fi


### LDAP
gislab_print_info "Deleting group"

# remove LDAP group
ldapdeletegroup $GISLAB_GROUP


# confirmation message
gislab_print_info "Group '$GISLAB_GROUP' was successfully deleted"

# vim: set ts=8 sts=4 sw=4 et:
