#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


### USAGE
function usage() {
    echo "USAGE: $(basename $0) [ -i ] [ COMMAND [ARG] ]"
    echo "Run command or launch interactive shell in GIS.lab client's chroot."
    echo -e "\nOPTIONS
    -i launch interactive shell in GIS.lab client's chroot. Other options will
       be ignored.
    -h display this help
    "
    exit 255
}


### OPTIONS
while getopts "ih" OPTION
do
    case "$OPTION" in
        i) opt_interactive="yes" ;;
        h) usage ;;
        \?) exit 1 ;;
    esac
done
if [ $# -eq 0 ]; then usage; fi

if [ -n "$opt_interactive" ]; then
    shift
    COMMAND="$@"

    if [ -n "$COMMAND" ]; then
        usage
    fi
else
    COMMAND="$@"
fi


### SANITY CHECKS
if [ ! -f "$GISLAB_PATH_SYSTEM/clients/desktop/root/etc/gislab_version" ]; then
    gislab_error "
        GIS.lab client chroot doesn't exist.
        GISLAB_SUITE must be set to 'lab' to build client image
    "
    exit 1
fi

if [ -f "$GISLAB_PATH_SYSTEM/clients/desktop/root/proc/version" ]; then
    gislab_error "
        Only one active GIS.lab client chroot session is allowed
    "
    exit 1
fi


### FUNCTIONS
function pre_chroot {
    chroot $GISLAB_PATH_SYSTEM/clients/desktop/root \
        mount -t devpts -o rw,noexec,nosuid,gid=5,mode=620 devpts /dev/pts
    chroot $GISLAB_PATH_SYSTEM/clients/desktop/root \
        mount -t proc proc /proc
    mount -o bind \
        $GISLAB_PATH_CACHE/packages/apt \
        $GISLAB_PATH_SYSTEM/clients/desktop/root/var/cache/apt

    # policy-rc.d
    cat <<EOF > $GISLAB_PATH_SYSTEM/clients/desktop/root/usr/sbin/policy-rc.d
#!/bin/sh
#

exit 101
EOF
    chmod +x $GISLAB_PATH_SYSTEM/clients/desktop/root/usr/sbin/policy-rc.d

    # start-stop-daemon
    mv -f \
        $GISLAB_PATH_SYSTEM/clients/desktop/root/sbin/start-stop-daemon \
        $GISLAB_PATH_SYSTEM/clients/desktop/root/sbin/start-stop-daemon.real
    cat <<EOF > $GISLAB_PATH_SYSTEM/clients/desktop/root/sbin/start-stop-daemon
#!/bin/sh
#

exit 0
EOF
    chmod +x $GISLAB_PATH_SYSTEM/clients/desktop/root/sbin/start-stop-daemon

    # launch interactive shell
    if [ "$opt_interactive" == "yes" ]; then
        gislab_info "
            Entering GIS.lab client chroot.
            Run 'exit' command or press 'CTRL-D' to exit
        "
    fi
}


function post_chroot {
    trap - 0 HUP INT QUIT KILL SEGV PIPE TERM

    chroot $GISLAB_PATH_SYSTEM/clients/desktop/root umount /dev/pts
    chroot $GISLAB_PATH_SYSTEM/clients/desktop/root umount /proc
    umount $GISLAB_PATH_SYSTEM/clients/desktop/root/var/cache/apt

    rm -f $GISLAB_PATH_SYSTEM/clients/desktop/root/usr/sbin/policy-rc.d
    mv -f \
        $GISLAB_PATH_SYSTEM/clients/desktop/root/sbin/start-stop-daemon.real \
        $GISLAB_PATH_SYSTEM/clients/desktop/root/sbin/start-stop-daemon

    if [ "$opt_interactive" == "yes" ]; then
        gislab_info "
            Leaving GIS.lab client chroot.
            Run 'gislab-client-image' to build client image from chroot
        "
    fi
}


### MAIN SCRIPT
pre_chroot
trap "post_chroot" 0 HUP INT QUIT KILL SEGV PIPE TERM
eval chroot $GISLAB_PATH_SYSTEM/clients/desktop/root $COMMAND

# vim: set ts=8 sts=4 sw=4 et:
