#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh


# require root privileges
gislab_require_root


# usage
function usage() {
	echo "USAGE: $(basename $0) [OPTIONS] group"
	echo "Create GIS.lab group. Group name can contain only lower case digits and numbers."
	echo -e "\nOPTIONS
	-d group description (optional)
	-h display this help
	"
	exit 255
}


# options
while getopts "d:h" OPTION
do
        case "$OPTION" in
			d) GISLAB_GROUP_DESCRIPTION="$OPTARG" ;;
			h) usage ;;
			\?) exit 1 ;;
        esac
done
shift $(($OPTIND - 1))
if [ $# -eq 0 ]; then usage; fi


GISLAB_GROUP=$1


# sanity checks
if getent group $GISLAB_GROUP > /dev/null 2>&1; then
	gislab_print_error "Cannot add group. Group '$GISLAB_GROUP' already exists"
	exit 1
fi

if ! [[ "$GISLAB_GROUP" =~ ^[a-z][a-z0-9_]*$ ]]; then
	gislab_print_error "Cannot add group. Invalid characters in group name"
	exit 1
fi


### LDAP
gislab_print_info "Adding group"

# create LDAP group
ldapaddgroup $GISLAB_GROUP

if [ -n "$GISLAB_GROUP_DESCRIPTION" ]; then
	ldapmodifygroup $GISLAB_GROUP > /dev/null << EOL
changetype: modify
add: description
description: $GISLAB_GROUP_DESCRIPTION
EOL
fi


# final message
gislab_print_info "Group '$GISLAB_GROUP' was successfully added"


# vim: set ts=4 sts=4 sw=4 noet:
