#!/bin/bash
# Open GIS.lab documentation

source /etc/gislab_version
ROOT_URL="http://gislab.readthedocs.io"
LANGUAGE="en"

firefox "$ROOT_URL/$LANGUAGE/latest" &

# TODO: uncomment lines below once documentation will be finished and
# localized. Until then latest English version should be always valid
# if [[ "$GISLAB_VERSION" =~ ^dev.* ]]; then firefox
# "$ROOT_URL/$LANGUAGE/latest" & else VERSION=$(echo $GISLAB_VERSION |
# awk -F '.' '{print $1 "." $2}') firefox
# "$ROOT_URL/$LANGUAGE/$VERSION" & fi

# vim: set ts=4 sts=4 sw=4 noet:
