#!/bin/bash

set -e

source /etc/gislab_version
source $GISLAB_ROOT/system/functions.sh

# require root privileges
gislab_require_root


### USAGE
function usage() {
    echo "USAGE: $(basename $0) [OPTIONS] app"
    echo "Start or stop GIS.lab known Docker applications."
    echo -e "\nOPTIONS
    -h  display this help
    -l  print known Docker applications
    -u  create and start Docker application. If value 'all' is given instead of
        app name, all known apps will be started
    -d  stop and remove Docker application.  If value 'all' is given instead of
        app name, all known apps will be stopped
    "
    exit 255
}


### OPTIONS
while getopts "ludh" OPTION
do
        case "$OPTION" in
            l) opt_action="list" ;;
            u) opt_action="up" ;;
            d) opt_action="down" ;;
            h) usage ;;
            \?) exit 1;;
        esac
done
shift $(($OPTIND - 1))
if ([ $# -eq 0 -a "$opt_action" != "list" ]) || [ -z "$opt_action" ]; then usage; fi


### VARIABLES
docker_dir=$GISLAB_PATH_SYSTEM/docker


### FUNCTIONS
function list_docker_apps {
    for dir in $(find $docker_dir -name docker-compose.yml); do
	da="$(dirname $dir)"
	echo "$(basename $da)"
    done
}

function check_docker_app {
    app="$1"
    if [[ ! " $(list_docker_apps) " =~ " ${app} " ]]; then
	gislab_error "$app is not known Docker application"
    fi
}

function _do_docker_app {
    dir="$1"
    op="$2"
    extra_op=
    (
	cd $docker_dir/$dir
	if [ "$op" == "up" ]; then
	    extra_op='-d --force-recreate'
	    ### docker-compose pull
	fi
	docker-compose $op $extra_op
    )
}

function do_docker_app {
    app="$1"
    op="$2"
    pull=0
    extra_op=

    if [ "$app" == "all" ]; then
	for da in $(list_docker_apps); do
	    _do_docker_app $da $op $extra_op
	done
    else
	check_docker_app $app
	_do_docker_app $app $op $extra_op
    fi
}


### MAIN SCRIPT
# LIST
if [ "$opt_action" == "list" ]; then
    echo "Known Docker applications:"
    for da in $(list_docker_apps); do
	echo -e "  * $da"
    done
else # UP/DOWN
    app="$1"
    do_docker_app $app "$opt_action"
    if [ "$app" == "all" ]; then
	pre="applications"
    else
	pre="application $app"
    fi
    if [ "$opt_action" == "up" ]; then
	op="started"
    else
	op="stopped"
    fi
    gislab_success "Docker $pre successfully $op"
fi

# vim: set ts=8 sts=4 sw=4 et:
