#!/bin/sh
#

for x in $(cat /proc/cmdline); do
    case "$x" in
        init=/sbin/init-gislab)
            GISLAB_BOOT=true
            break
            ;;
    esac
done

test -z $GISLAB_BOOT && exit

[ -z "${rootmnt}" ] && panic "rootmnt unknown in init-bottom"
[ -d "${rootmnt}/proc" ] || panic "rootmnt not mounted in init-bottom"
# mount writeable filesystems if / is not already mounted writeable.
if ! chroot ${rootmnt} /usr/bin/test -w "/" ; then
    mkdir -p /rofs /cow
    mount -t tmpfs -o mode=0755 tmpfs /cow
    mount -o move ${rootmnt} /rofs
    # detect which unionfs to use
    while read x ; do
        for y in $x ; do
            case $y in
                aufs)
                    UNION_TYPE=aufs
                    UNION_OPTS="dirs=/cow=rw:/rofs=ro"
                    ;;
                overlayfs) 
                    UNION_TYPE=overlayfs
                    UNION_OPTS="upperdir=/cow,lowerdir=/rofs"
                    ;;
            esac
        done
    done < /proc/filesystems
    mount -t ${UNION_TYPE} -o ${UNION_OPTS} ${UNION_TYPE} ${rootmnt}
    for dir in /rofs /cow ; do
        mkdir -p ${rootmnt}${dir}
        mount -o move ${dir} ${rootmnt}${dir}
    done
fi

mkdir -p "$rootmnt/var/cache/gislab"
cp /tmp/net-*.conf "$rootmnt/var/cache/gislab/"

# vim: set ts=8 sts=4 sw=4 et:
